# Site settings
title: Clean Blog
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "http://fistbumpteam.github.io"
url: "http://fistbumpteam.github.io"
github_username:  fistbumpteam

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
